# 绳包管理器后端配置文件
# 服务器配置
[server]
host = "127.0.0.1"
port = 15201
workers = 4
timeout = 30

# 数据库配置
[database]
url = "data.db"
max_connections = 10
timeout = 30

# 认证配置
[auth]
jwt_secret = "your-secret-key-change-in-production"
jwt_expiration = 86400  # 24小时
bcrypt_cost = 12

# 文件配置
[file]
upload_path = "uploads"
max_file_size = 10485760  # 10MB
allowed_extensions = ["zip", "rar", "7z", "tar", "gz"]
temp_path = "temp"

# 日志配置
[logging]
level = "info"
file_path = "logs/app.log"
max_files = 5
max_size = 10485760  # 10MB

# CORS配置
[cors]
allowed_origins = ["*"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowed_headers = ["Content-Type", "Authorization", "X-Requested-With"]
max_age = 3600 