/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BannerSwiper: typeof import('./src/components/BannerSwiper.vue')['default']
    CategoryList: typeof import('./src/components/CategoryList.vue')['default']
    ResourceCard: typeof import('./src/components/ResourceCard.vue')['default']
    ResourceList: typeof import('./src/components/ResourceList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
  }
}
