/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommunityLink: typeof import('./src/components/community/CommunityLink.vue')['default']
    CommunityNav: typeof import('./src/components/community/CommunityNav.vue')['default']
    ContentCard: typeof import('./src/components/home/ContentCard.vue')['default']
    DataTable: typeof import('./src/components/common/DataTable.vue')['default']
    ElderSideBar: typeof import('./src/components/layout/ElderSideBar.vue')['default']
    HomeFooter: typeof import('./src/components/home/HomeFooter.vue')['default']
    HomeHeader: typeof import('./src/components/home/HomeHeader.vue')['default']
    HomeMainContent: typeof import('./src/components/home/HomeMainContent.vue')['default']
    HomeSidebar: typeof import('./src/components/home/HomeSidebar.vue')['default']
    LoadingSkeleton: typeof import('./src/components/LoadingSkeleton.vue')['default']
    NavBar: typeof import('./src/components/layout/NavBar.vue')['default']
    PermissionGuard: typeof import('./src/components/PermissionGuard.vue')['default']
    RightSidebar: typeof import('./src/components/home/RightSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/layout/SideBar.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    UserMenu: typeof import('./src/components/home/UserMenu.vue')['default']
    UserNavBar: typeof import('./src/components/layout/UserNavBar.vue')['default']
    UserSideBar: typeof import('./src/components/layout/UserSideBar.vue')['default']
  }
}
