[server]
host = "127.0.0.1"
port = 15201
workers = 4

[database]
url = "sqlite:./data/app.db"
max_connections = 20
min_connections = 5
acquire_timeout = 30
idle_timeout = 300
max_lifetime = 1800

[storage]
upload_path = "./uploads"
temp_path = "./temp"
max_file_size = 52428800
allowed_extensions = ["zip", "rar", "7z", "tar", "gz", "jpg", "jpeg", "png", "gif", "webp"]

[jwt]
secret = "your-secret-key-change-in-production"
expires_in = 86400
refresh_expires_in = 604800

[cache]
redis_url = "redis://127.0.0.1:6379"
default_ttl = 3600

[email]
smtp_host = "smtp.qq.com"
smtp_port = 587
smtp_username = ""
smtp_password = ""
from_address = "noreply@jieshen.com"
from_name = "绳包管理器"

[logging]
level = "info"
file_enabled = true
file_path = "./logs"
console_enabled = true
json_format = false
with_file_info = true
with_thread_ids = true
with_timestamps = true 